services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"     
      - "29092:29092" 
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

  spark-master:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./streaming:/opt/spark/work-dir/streaming
      - ./batch:/opt/spark/work-dir/batch
      - ./models:/opt/spark/work-dir/models
    environment:
      - PYTHONPATH=/opt/spark/work-dir
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    command: ["bash", "-c", "mkdir -p /opt/spark/work-dir/models && /opt/spark/bin/spark-submit /opt/spark/work-dir/streaming/spark_streaming.py"]

  spark-worker:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile
    container_name: spark-worker
    depends_on:
      - spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    ports:
      - "8081:8081"
    environment:  
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    volumes:
      - ./streaming:/opt/spark/work-dir/streaming

  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
    ports:
      - "9870:9870"
    volumes:
      - ./hadoop_data/namenode:/hadoop/dfs/name

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode
    depends_on:
      - hdfs-namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
    ports:
      - "9864:9864"
    volumes:
      - ./hadoop_data/datanode:/hadoop/dfs/data

  # hbase:
  #   image: dajobe/hbase:latest
  #   container_name: hbase
  #   ports:
  #     - "16010:16010" 
  #     - "9090:9090"   
  #   environment:
  #     - HBASE_MANAGES_ZK=true
  #   volumes:
  #     - ./hbase-data:/opt/hbase-data

  hbase:
    image: harisekhon/hbase:latest
    container_name: hbase
    environment:
      #HBASE_HEAPSIZE: 1G
      HBASE_MANAGES_ZK: "true"
    ports:
      - "9090:9090"
      - "16010:16010"
    volumes:
      - ./hbase-data:/opt/hbase-data
    # command: >
    #   bash -c "start-hbase.sh && hbase-daemon.sh start thrift && tail -f /dev/null"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
    - ./mongo-data:/data/db

  producer:
    container_name: crypto-producer
    build:
      context: ./docker/crypto-producer
    depends_on:
      - kafka
    restart: unless-stopped

  flask:
    container_name: crypto-dashboard
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - HBASE_THRIFT_HOST=hbase
      - HBASE_THRIFT_PORT=9090
      - MONGO_HOST=mongodb
    volumes:
    - ./models:/app/models
    depends_on:
      - hbase
      - mongodb
      
  streamlit:
    build:
      context: .
      dockerfile: docker/streamlit/Dockerfile  # CHỈ dùng Dockerfile này
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
    volumes:
      - .:/app  # Đảm bảo batch/streamlit_batch_dashboard.py tồn tại trong container

  airflow:
    image: apache/airflow:2.9.1-python3.10
    container_name: airflow
    depends_on:
      - spark-master
    ports:
      - "3636:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "
        airflow db migrate &&
        airflow standalone
      "


volumes:
  namenode:
    driver: local
  datanode:
    driver: local